# Generated by Django 4.0.3 on 2022-03-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='imgurl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
