# Generated by Django 4.0.3 on 2022-03-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyapi', '0002_alter_interview_collection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyuser',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='keyapi.field'),
        ),
        migrations.AlterField(
            model_name='keyuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='keyapi.institution'),
        ),
    ]
